config/routes.rb
Rails.application.routes.draw do
  resources :airlines, only: [:index]
  resources :flights, only: [:create]
  resources :departures, only: [:index]
  resources :arrivals, only: [:index]
end

app/models/airline.rb
# == Schema Information
#
# Table name: airlines
#
#  id         :integer          not null, primary key
#  name       :string
#  logo_url   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airline < ActiveRecord::Base
end

app/models/arrival.rb
# == Schema Information
#
# Table name: arrivals
#
#  id         :integer          not null, primary key
#  flight_id  :integer
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  date       :datetime
#  gate       :integer
#

class Arrival < ActiveRecord::Base
  belongs_to :flight
  has_one :airline, through: :flight

  enum status: { on_time: 0 , delayed: 1 , landing: 2, landed: 3 }

  def str_status
    { on_time: "A Tiempo", delayed: "Demorado", landing: "Aterrizando", landed: "Aterrizó" }[status.to_sym]
  end
end

app/models/departure.rb
# == Schema Information
#
# Table name: departures
#
#  id         :integer          not null, primary key
#  flight_id  :integer
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  date       :datetime
#  gate       :integer
#

class Departure < ActiveRecord::Base
  belongs_to :flight
  has_one :airline, through: :flight

  enum status: { closed: 0, on_gate: 1, boarding: 2, took_off: 3, delayed: 4 }

  def str_status
    { closed: "Cerrado", on_gate: "En Sala", boarding: "Abordando", took_off: "Despegó", delayed: "Demorado" }[status.to_sym]
  end
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id         :integer          not null, primary key
#  airline_id :integer
#  number     :string(10)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Flight < ActiveRecord::Base
  belongs_to :airline
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/arrivals_controller.rb
class ArrivalsController < ApplicationController
  def index
    @arrivals = Arrival.all
  end
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  def index
    @departures = Departure.all
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arrivals_helper.rb
module ArrivalsHelper

  def arrival_class(arrival)
    return "danger" if arrival.delayed?
    return "success" if arrival.landed?
  end
end

app/helpers/departures_helper.rb
module DeparturesHelper
  def departure_class(departure)
    "danger" if departure.delayed?
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/arrivals/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Llegadas Nacionales</h1>

      <table class="table table-hover flights">
        <thead>
          <tr>
            <th>Airline</th>
            <th>Flight</th>
            <th>Status</th>
            <th class="text-center">Time</th>
            <th class="text-center">Gate</th>
          </tr>
        </thead>
        <tbody>
          <% @arrivals.each do |arrival| %>
          <tr class="<%= arrival_class(arrival) %>">
            <td class="airline-logo"><img src="<%= arrival.airline.logo_url %>" /></td>
            <td><%= arrival.flight.number %></td>
            <td><%= arrival.str_status %></td>
            <td class="text-center"><%= l arrival.date, format: '%H:%M' %></td>
            <td class="text-center"><%= arrival.gate %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/departures/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Salidas Internacionales</h1>

      <table class="table flights">
        <thead>
          <tr>
            <th>Airline</th>
            <th>Flight</th>
            <th>Status</th>
            <th class="text-center">Time</th>
            <th class="text-center">Gate</th>
          </tr>
        </thead>
        <tbody>
          <% @departures.each do |departure| %>
          <tr class="<%= departure_class(departure) %>">
            <td class="airline-logo"><img src="<%= departure.airline.logo_url %>" /></td>
            <td><%= departure.flight.number %></td>
            <td><%= departure.str_status %></td>
            <td class="text-center"><%= l departure.date, format: '%H:%M' %></td>
            <td class="text-center"><%= departure.gate %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-plane"></span></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Aerolíneas", airlines_path %></li>
          <li><%= link_to "Salidas", departures_path %></li>
          <li><%= link_to "Llegadas", arrivals_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Salir</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<%= yield %>

</body>
</html>